development:
  adapter: postgresql
  encoding: unicode
  database: myapp_dev
  pool: 5
  host: localhost
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username:
  password: 